### ISSUE TITLE
TypeError: _.pickBy is not a function

### ISSUE THREAD

**Issue by matthewbennink** [heroku/heroku-cli-addons#13]
I tried listing the add-ons for an app and saw the following -

```
 !   Error in heroku-cli-addons:
 !   _.pickBy is not a function
 !   See /Users/matt/.heroku/error.log for more info.
```

I then tried re-installing the plugin and received the following.  Minimal googling suggests that `pickBy` isn't available until lodash 4.x but this project's package.json seems to depend on 3.x.

```
➜  .heroku heroku plugins:install heroku-cli-addons
Installing plugin heroku-cli-addons...
 ▸    Error reading plugin: heroku-cli-addons
 ▸    exit status 1
 ▸    /Users/matt/.heroku/node_modules/heroku-cli-addons/node_modules/heroku-cli-util/lib/color.js:12
 ▸    let definedColors = _.pickBy(colors, function(value) {
 ▸                          ^
 ▸
 ▸    TypeError: _.pickBy is not a function
 ▸        at Object.<anonymous> (/Users/matt/.heroku/node_modules/heroku-cli-addons/node_modules/heroku-cli-util/lib/color.js:12:23)
 ▸        at Module._compile (module.js:413:34)
 ▸        at Object.Module._extensions..js (module.js:422:10)
 ▸        at Module.load (module.js:357:32)
 ▸        at Function.Module._load (module.js:314:12)
 ▸        at Module.require (module.js:367:17)
 ▸        at require (internal/module.js:16:19)
 ▸        at Object.<anonymous> (/Users/matt/.heroku/node_modules/heroku-cli-addons/node_modules/heroku-cli-util/index.js:19:28)
 ▸        at Module._compile (module.js:413:34)
 ▸        at Object.Module._extensions..js (module.js:422:10)
 !    error installing plugin heroku-cli-addons
```

**Comment by matthewbennink** [comment]
OK, sorry, I just realized this error was coming from a dependency, not heroku-cli-addons itself.  Will look at the heroku-cli-util project!
